### ISSUE TITLE
Commit function broken with more than one flags

### ISSUE THREAD

**Issue by annagray** [bookchin/gitty#60]
I was using the gitty repo to save information to another git repository and ran into an issue when trying to commit with additional flags like --author.

Example of calling commit function:
`flags =  [--author="Sample Author"]`
`repo.commit(message, flags, callback)`

When no flags are specified, the code works as expected because an array with -m is passed back. But, when trying to call the commit function with an array of flags specified, the code base returns flags.push('-m').  The push function, however, returns the new length of the array rather than the array itself.  Instead this should use the concat function which returns the new array. 

Line 273 in gitty/lib/repository.js: (original --> fix)
`var flags = Array.isArray(args[1]) ? args[1].push('-m') : ['-m'];`
`var flags = Array.isArray(args[1]) ? args[1].concat('-m') : ['-m'];`

**Comment by bookchin** [comment]
Ah, good find, thanks!

**Comment by annagray** [comment]
No problem! Would you like me to create a pull request or are you able to update it?

**Comment by bookchin** [comment]
If you have time, I'd happily merge a PR! Be sure to add yourself to the contributor list in the package.json. :)

**Comment by annagray** [comment]
Sure sounds good, will do!

**Comment by bookchin** [comment]
Closed by @annagray #61
